### ISSUE TITLE
v covidDataTotal se zobrazují neaktuální data

### ISSUE THREAD

**Issue by vonStichen** [covid19cz/erouska-backend#105]
Na adrese https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/zakladni-prehled.json, kde získáváme JSON od ÚZIS proběhla aktualizace 6.10. v 18:00 (první přiložený screenshot z JSONu má datum aktualizace 18:11).

V collection [`covidDataTotal`](https://github.com/covid19cz/erouska-backend/wiki/database), kterou jsem otevřel ve 20:00 se ale pro 6.10. zobrazují neaktuální data (viz druhý screenshot).

Tento stav zdá se poukazuje na to, že funkce [`getCovidData`](https://github.com/covid19cz/erouska-backend/wiki/Firebase-Functions) se nespouští každou hodinu (což by měla).

![image](https://user-images.githubusercontent.com/44162139/95241886-b8ec7280-080e-11eb-9568-8be4a817899d.png)

![image](https://user-images.githubusercontent.com/44162139/95241850-aa9e5680-080e-11eb-812b-c880154e07f5.png)

**Comment by jendakol** [comment]
@vranystepan Vidím v konzoli, že `DownloadCovidDataTotal` se nasadilo naposledy 30.9.2020, nezapomněl jsi to nasadit, když jsi mi 2.10. říkal, že to děláš? :-D I na GH chybí release.

Jiný problém je, že to bohužel nefunguje ani když funkci pustím ručně. Podle mě je [chyba v implementaci](https://github.com/covid19cz/erouska-backend/blob/main/internal/functions/coviddata/download-covid-data-total.go#L142), kdy se data zapíšou pouze pokud v DB nejsou, ale nikdy nedojde k jejich přepsání. Ten kód vypadá, jako že by to mohl být úmysl, ale spíš se jedná o chybu a v současné chvíli je to každopádně nežádoucí. @vranystepan nebo @marekaf prosím ověřte mojí teorii a ASAP opravíme.

**Comment by marekaf** [comment]
@jendakol funkce se nemenila, menil se jenom scheduler v terraformu, to @vranystepan nasadil https://github.com/covid19cz/erouska-backend/commit/510662e7ce41652c885230272d2ea7ed3a43cad8

**Comment by marekaf** [comment]
@jendakol chyba v implementaci neni, je to feature :D byl umysl to neprepisovat kdyz se to zavola vickrat. Jestli je to ted nezadouci, tak to, prosim, uprav.

**Comment by marekaf** [comment]
and let's keep the communication here in english pls:)

**Comment by jendakol** [comment]
Oh. I'm still confused by the fact you're not applying terraform as part of the build :smile: OK, so it's about the code then. Please review PR #106 which should do the trick.
