### ISSUE TITLE
Connect functions together - `registerNotification`

### ISSUE THREAD

**Issue by jendakol** [covid19cz/erouska-backend#15]
Function [`registerNotification`](https://github.com/covid19cz/erouska-backend/wiki/Firebase-Functions#registernotification) internally calls some other functions (such as [`increaseIpAttemptsCount`](https://github.com/covid19cz/erouska-backend/wiki/Firebase-Functions#increaseipattemptscount).  
Wire them together, when they are all ready.

**Comment by marekaf** [comment]
@jendakol would it make more sense to call `increaseIpAttemptsCount` on a firestore trigger event (on registration collection) rather than call it directly from the function?

**Comment by jendakol** [comment]
@marekaf I think that's a good idea.

**Comment by marekaf** [comment]
@jendakol aaah, but we don't have the `IP` in the collection, only eHrid

**Comment by jendakol** [comment]
You mean you'd need to save the IP into the collection together with the timestamp? Technically, why not. But I'm not sure if that's not somehow GDPR problematic....

**Comment by marekaf** [comment]
> You mean you'd need to save the IP into the collection together with the timestamp? Technically, why not. But I'm not sure if that's not somehow GDPR problematic....

Yep, I think it does not make any sense. I'm thinking about using Pub/sub - I'll publish messages in different topics (different topics for different functions) and they'll trigger their function. It would mean to change `increaseIpAttemptsCount` (and the other funcs) to PubSub trigger instead of http.

**Comment by jendakol** [comment]
Sounds good :+1:
