### ISSUE TITLE
Authentication for `ProvideVerificationCode` function

### ISSUE THREAD

**Issue by jendakol** [covid19cz/erouska-backend#24]
Pre-discussed with Jiří Halvíček (Daktela).  
Possibilities:
a) IP whitelisting + API key
b) [Cloud functions authentication](https://cloud.google.com/functions/docs/securing/authenticating#service-to-function)

**Comment by marekaf** [comment]
@jendakol this is probably not needed anymore, correct?

**Comment by jendakol** [comment]
Like you say.
