### ISSUE TITLE
Wrong error json being returned

### ISSUE THREAD

**Issue by marekaf** [covid19cz/erouska-backend#40]
json with "status" and "message" should be returned in case of an error, but "code" and "message" are being returned instead

**Comment by marekaf** [comment]
https://github.com/covid19cz/erouska-backend/blob/develop/internal/utils/http/http.go#L169 
so should we return code or status? 
cc @jendakol

**Comment by ashhanai** [comment]
According to firebase documentation (https://firebase.google.com/docs/functions/callable-reference#response_body) you should return `status` and `message`. `code` field shall not be included at all.

**Comment by marekaf** [comment]
https://github.com/covid19cz/erouska-backend/blob/develop/internal/utils/errors/errors.go#L16
sometimes we return this struct, wrapping it in error, resulting in something like
```
{"error":{"code":3,"message":"Validation of the request has failed: validator: (nil)"}}%
```

**Comment by jendakol** [comment]
@marekaf As you may see, I've used official struct for the error expressing - and it contains `code` and `message`. It seems like even in Google they have quite a mess in this.  
Anyway, if @ashhanai is experiencing any troubles and official docs say it should be done differently, I'll change it - sure thing.
