### ISSUE TITLE
add error reporting / alerting / monitoring

### ISSUE THREAD

**Issue by marekaf** [covid19cz/erouska-backend#59]
Stackdriver Error Reporting to email would be sufficient I guess
I definitely need to know if the data generating jobs for GetCovidData fail and I need to be alerted immediately.

**Comment by marekaf** [comment]
there is some http monitoring in verification server (coming from the upstream), I deployed it yesterday, it notifies my email address
still it would be great to have some alerting for DownloadCovidData, cc @vranystepan if you want to take this :)

**Comment by jendakol** [comment]
It's in progress (finally).
