### ISSUE TITLE
remove selected daily increase metrics

### ISSUE THREAD

**Issue by vonStichen** [covid19cz/erouska-backend#68]
The following metrics are to be removed from the collection [`covidDataIncrease`](https://github.com/covid19cz/erouska-backend/wiki/database#covidDataIncrease):

- `activeCasesIncrease` (Int)
- `curedIncrease` (Int)
- `deceasedIncrease` (Int)
- `currentlyHospitalizedIncrease` (Int)

**Comment by dizider** [comment]
Solved in #69. Collection `covidDataIncrease` completely removed.
